{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: genome-sampler
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - vsearch
    - pandas
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*
    - q2templates {{ release }}.*

test:
  imports:
    - genome_sampler
    - qiime2.plugins.genome_sampler

about:
  home: https://github.com/caporaso-lab/genome-sampler
  license: BSD-3-Clause
  license_family: BSD
