# Book settings
title                       : genome-sampler documentation
author                      : The genome-sampler developers
copyright                   : "2020"  # Copyright year to be placed in the footer

#######################################################################################
# HTML-specific settings
html:
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : "UA-86713402-2"  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://caporasolab.us/genome-sampler/"

repository:
  url                       : https://github.com/caporaso-lab/genome-sampler  # The URL to your book's repository
  path_to_book              : "docs"  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links
